version: '2'
services:
    trustyourself-app:
        image: trustyourself
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://trustyourself-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=trustYourself
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trustyourself-mongodb:
        extends:
            file: mongodb.yml
            service: trustyourself-mongodb
